local rb = require("rootbeer")
local zsh = require("rootbeer.shells.zsh")
local d = rb.data()

-- High-level module API
zsh.comment("Generated by rootbeer for " .. d.hostname)
zsh.env("PATH", "/usr/local/bin:$PATH")
zsh.env("EDITOR", "nvim")

if d.os == "Darwin" then
	zsh.env("HOMEBREW_PREFIX", "/opt/homebrew")
	zsh.eval("/opt/homebrew/bin/brew shellenv")
end

zsh.alias("ls", "ls -la")
zsh.alias("g", "git")
zsh.alias("v", "nvim")

zsh.source("~/.config/zsh/local.zsh")

-- You can always drop down to primitives
rb.line("")
rb.line("# Raw primitives still work alongside modules")
rb.line("autoload -Uz compinit && compinit")
