local rb = require("rootbeer")

-- Test rb.data()
local d = rb.data()
print("OS: " .. d.os)
print("Arch: " .. d.arch)
print("Hostname: " .. d.hostname)
print("Home: " .. d.home)
print("User: " .. d.username)

-- Test rb.line() and rb.emit()
rb.line("# Generated by rootbeer")
rb.line("export PATH=/usr/local/bin:$PATH")

if d.os == "Darwin" then
	rb.line("export HOMEBREW_PREFIX=/opt/homebrew")
end

rb.emit("# This was emitted raw, no trailing newline")
