#!/usr/bin/env python3
import sys
import os

outfile = sys.argv[1]
sources = sys.argv[2:]

with open(outfile, 'w') as f:
    f.write("// Auto-generated by Meson\n")
    f.write('#include "cli_module.h"\n\n')

    names = []
    for path in sources:
        name = os.path.splitext(os.path.basename(path))[0]
        f.write(f"extern rb_cli_cmd {name};\n")
        names.append(name)

    f.write("\nrb_cli_cmd *rb_cli_cmds[] = {\n")
    for name in names:
        f.write(f"    &{name},\n")
    f.write("    NULL\n};\n")
