[settings]
idiomatic_version_file_enable_tools = ["rust", "node", "pnpm"]

[tools]
lua-language-server = "latest"
lefthook = "latest"
stylua = "latest"
"aqua:Kampfkarren/selene" = "latest"

[env]
_.path = ["./target/debug"]
