[package]
name = "rootbeer-build"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
rootbeer-store = { path = "../rootbeer-store" }
rootbeer-package = { path = "../rootbeer-package" }
flate2 = "1"
tar = "0.4"
libc = "0.2.182"
goblin = { version = "0.10.7", default-features = false, features = ["std", "elf32", "elf64", "mach32", "mach64", "endian_fd"] }

[build-dependencies]
sha2 = "0.10"
