[package]
name = "rootbeer-packaging"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
ring = "0.17.14"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
rootbeer-store = { path = "../rootbeer-store" }
rootbeer-package = { path = "../rootbeer-package" }
rootbeer-build = { path = "../rootbeer-build" }
ureq = "3"
[dev-dependencies]
flate2 = "1"
tar = "0.4"
