use std::path::PathBuf;
use std::{env, fs};

fn main() {
    #[cfg(not(unix))]
    compile_error!("rootbeer only supports unix-like systems (macOS, Linux)");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let lua_dir = manifest_dir.join("../../lua");
    let lua_dir = lua_dir.canonicalize().expect("lua/ directory not found");

    println!("cargo:rustc-env=ROOTBEER_LUA_DIR={}", lua_dir.display());
    println!("cargo:rerun-if-changed={}", lua_dir.display());

    if env::var("CARGO_FEATURE_EMBEDDED_STDLIB").is_ok() {
        let rootbeer_dir = lua_dir.join("rootbeer");
        let mut entries: Vec<(String, String)> = fs::read_dir(&rootbeer_dir)
            .expect("Failed to read lua/rootbeer directory")
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().is_some_and(|ext| ext == "lua"))
            .filter_map(|e| {
                let path = e.path().canonicalize().ok()?;
                let name = path.file_stem()?.to_str()?.to_owned();
                Some((name, path.display().to_string()))
            })
            .collect();

        entries.sort_by(|a, b| a.0.cmp(&b.0));
        let body = entries
            .iter()
            .map(|(name, path)| format!(r#" ("{name}", include_str!("{path}")),"#))
            .collect::<Vec<_>>()
            .join("\n");

        let generated = format!(
            "// This file is generated by build.rs. Do not edit manually.\n\
             const EMBEDDED_MODULES: &[(&str, &str)] = &[\n\
             {body}\n\
             ];\n"
        );

        let out_dir = PathBuf::from(
            env::var("OUT_DIR").expect("OUT_DIR environment variable not set by Cargo"),
        );

        let dest_path = out_dir.join("embedded_modules.rs");
        fs::write(&dest_path, generated).expect("Failed to write embedded_modules.rs");
    }
}
