#!/usr/bin/env python3
import sys

outfile = sys.argv[1]
sources = sys.argv[2:]

with open(outfile, 'w') as f:
    f.write("// Auto-generated by Meson\n")
    f.write('#include "rb_plugin.h"\n\n')

    for name in sources:
        f.write(f"extern const rb_plugin_t rb_plugin_{name};\n")

    f.write("\nconst rb_plugin_t *rb_plugins[] = {\n")
    for name in sources:
        f.write(f"    &rb_plugin_{name},\n")
    f.write("    NULL\n};\n")
