use std::fs;
use std::io;
use std::path::{Path, PathBuf};

pub fn dir() -> PathBuf {
    crate::state_dir()
        .join("profiles")
        .join("default")
        .join("current")
}

pub fn bin_dir() -> PathBuf {
    dir().join("bin")
}

pub fn bin_path(bin: &str) -> PathBuf {
    bin_dir().join(bin)
}

pub fn env_path() -> PathBuf {
    dir().join("env.sh")
}

pub fn env_path_for_bin_dir(bin_dir: &Path) -> PathBuf {
    bin_dir
        .parent()
        .map(|profile| profile.join("env.sh"))
        .unwrap_or_else(env_path)
}

pub fn env_contents() -> String {
    env_contents_for_bin_dir(&bin_dir())
}

pub fn write_env_file() -> io::Result<()> {
    write_env_file_for_bin_dir(&bin_dir())
}

pub fn write_env_file_for_bin_dir(bin_dir: &Path) -> io::Result<()> {
    let path = env_path_for_bin_dir(bin_dir);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, env_contents_for_bin_dir(bin_dir))
}

fn env_contents_for_bin_dir(bin_dir: &Path) -> String {
    let quoted = shell_single_quote(&bin_dir.to_string_lossy());
    format!(
        "# Generated by rootbeer; do not edit.\n_rootbeer_package_bin={quoted}\ncase \":$PATH:\" in\n  *:\"$_rootbeer_package_bin\":*) ;;\n  *) export PATH=\"$_rootbeer_package_bin:$PATH\" ;;\nesac\nunset _rootbeer_package_bin\n"
    )
}

fn shell_single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn env_file_prepends_package_bin_once() {
        let contents = env_contents_for_bin_dir(Path::new("/tmp/root beer/bin"));

        assert!(contents.contains("_rootbeer_package_bin='/tmp/root beer/bin'"));
        assert!(contents.contains("case \":$PATH:\" in"));
        assert!(contents.contains("export PATH=\"$_rootbeer_package_bin:$PATH\""));
    }
}
