name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - "src"
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.14.0
        continue-on-error: true
        with:
          clang-format-version: "13"
          check-path: ${{ matrix.path }}
          fallback-style: "LLVM" # optional
